export const ErrorCodes = {
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    AUTH_INVALID: 'AUTH_INVALID',
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    TASK_NOT_CANCELLABLE: 'TASK_NOT_CANCELLABLE',
    AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
    AGENT_ALREADY_EXISTS: 'AGENT_ALREADY_EXISTS',
    AGENT_ALREADY_RUNNING: 'AGENT_ALREADY_RUNNING',
    AGENT_LIMIT_REACHED: 'AGENT_LIMIT_REACHED',
    SEND_FAILED: 'SEND_FAILED',
    KEY_LOCKED: 'KEY_LOCKED',
    KEY_NOT_FOUND: 'KEY_NOT_FOUND',
    CONNECTION_LOST: 'CONNECTION_LOST',
    INVALID_REQUEST: 'INVALID_REQUEST',
    WALLET_NOT_AUTHORIZED: 'WALLET_NOT_AUTHORIZED',
    WALLET_AUTHORIZATION_EXPIRED: 'WALLET_AUTHORIZATION_EXPIRED',
    WALLET_PROGRAM_NOT_ALLOWED: 'WALLET_PROGRAM_NOT_ALLOWED',
    WALLET_REQUIRES_MASTER_APPROVAL: 'WALLET_REQUIRES_MASTER_APPROVAL',
    WALLET_DAILY_LIMIT_EXCEEDED: 'WALLET_DAILY_LIMIT_EXCEEDED',
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
    WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
    PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
    PAYMENT_INVALID_STATE: 'PAYMENT_INVALID_STATE',
    PAYMENT_UNAUTHORIZED: 'PAYMENT_UNAUTHORIZED',
    PAYMENT_NOT_ALLOWED: 'PAYMENT_NOT_ALLOWED',
    SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
    SETTLEMENT_INVALID_STATE: 'SETTLEMENT_INVALID_STATE',
    SETTLEMENT_FAILED: 'SETTLEMENT_FAILED',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    SOLANA_ERROR: 'SOLANA_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class DaemonError extends Error {
    constructor(
        public readonly code: ErrorCode,
        message: string,
        public readonly statusCode: number = 500,
    ) {
        super(message);
        this.name = 'DaemonError';
    }
}
