/**
 * Generates TypeScript and Rust clients from the Codama IDL.
 */

import type { AnchorIdl } from '@codama/nodes-from-anchor';
import { renderVisitor as renderJavaScriptVisitor } from '@codama/renderers-js';
import { renderVisitor as renderRustVisitor } from '@codama/renderers-rust';
import fs from 'fs';
import path from 'path';

import { createPinocchioCounterCodamaBuilder } from './lib/pinocchio-counter-codama-builder';
import { preserveConfigFiles } from './lib/utils';

const projectRoot = path.join(__dirname, '..');
const idlDir = path.join(projectRoot, 'idl');
const pinocchioCounterIdl = JSON.parse(
    fs.readFileSync(path.join(idlDir, 'pinocchio_counter.json'), 'utf-8'),
) as AnchorIdl;
const rustClientsDir = path.join(__dirname, '..', 'clients', 'rust');
const typescriptClientsDir = path.join(__dirname, '..', 'clients', 'typescript');

const pinocchioCounterCodama = createPinocchioCounterCodamaBuilder(pinocchioCounterIdl)
    .appendAccountDiscriminator()
    .appendPdaDerivers()
    .setInstructionAccountDefaultValues()
    .updateInstructionBumps()
    .removeEmitInstruction()
    .build();

void main();

async function main(): Promise<void> {
    const configPreserver = preserveConfigFiles(typescriptClientsDir, rustClientsDir);
    try {
        await pinocchioCounterCodama.accept(
            renderRustVisitor(path.join(rustClientsDir, 'src', 'generated'), {
                crateFolder: rustClientsDir,
                deleteFolderBeforeRendering: true,
                formatCode: true,
            }),
        );

        await pinocchioCounterCodama.accept(
            renderJavaScriptVisitor(path.join(typescriptClientsDir, 'src', 'generated'), {
                deleteFolderBeforeRendering: true,
                formatCode: true,
            }),
        );
    } finally {
        configPreserver.restore();
    }

    applyGradienceClientFixups(typescriptClientsDir, rustClientsDir);
}

function applyGradienceClientFixups(
    typescriptClientDir: string,
    rustClientDir: string,
): void {
    const generatedDir = path.join(typescriptClientDir, 'src', 'generated');
    const pdasDir = path.join(generatedDir, 'pdas');
    const typesDir = path.join(generatedDir, 'types');

    fs.mkdirSync(pdasDir, { recursive: true });
    fs.mkdirSync(typesDir, { recursive: true });

    fs.writeFileSync(
        path.join(pdasDir, 'index.ts'),
        `import { getProgramDerivedAddress, type Address } from '@solana/kit';\n\nimport { GRADIENCE_PROGRAM_ADDRESS } from '../programs/gradience.js';\n\nexport async function findEventAuthorityPda(\n    programAddress: Address = GRADIENCE_PROGRAM_ADDRESS,\n): Promise<Address> {\n    const [pda] = await getProgramDerivedAddress({\n        programAddress,\n        seeds: [new TextEncoder().encode('event_authority')],\n    });\n    return pda;\n}\n`,
    );

    fs.writeFileSync(
        path.join(typesDir, 'pubkeyBytes.ts'),
        `import {\n    getArrayDecoder,\n    getArrayEncoder,\n    getU8Decoder,\n    getU8Encoder,\n    type Decoder,\n    type Encoder,\n} from '@solana/kit';\n\nexport type PubkeyBytes = number[];\nexport type PubkeyBytesArgs = number[];\n\nexport function getPubkeyBytesEncoder(): Encoder<PubkeyBytesArgs> {\n    return getArrayEncoder(getU8Encoder(), { size: 32 });\n}\n\nexport function getPubkeyBytesDecoder(): Decoder<PubkeyBytes> {\n    return getArrayDecoder(getU8Decoder(), { size: 32 });\n}\n`,
    );

    appendExport(path.join(generatedDir, 'index.ts'), 'export * from "./pdas";');
    appendExport(path.join(typesDir, 'index.ts'), 'export * from "./pubkeyBytes";');

    const rustTypesDir = path.join(rustClientDir, 'src', 'generated', 'types');
    fs.writeFileSync(
        path.join(rustTypesDir, 'pubkey_bytes.rs'),
        `//! This code was AUTOGENERATED using the codama library.\n//! Please DO NOT EDIT THIS FILE, instead use visitors\n//! to add features, then rerun codama to update it.\n//!\n//! <https://github.com/codama-idl/codama>\n//!\n\npub type PubkeyBytes = [u8; 32];\n`,
    );
    appendRustMod(path.join(rustTypesDir, 'mod.rs'), 'pub(crate) mod r#pubkey_bytes;');
    appendRustUse(path.join(rustTypesDir, 'mod.rs'), 'pub use self::r#pubkey_bytes::*;');
}

function appendExport(filePath: string, exportLine: string): void {
    const current = fs.readFileSync(filePath, 'utf-8');
    if (current.includes(exportLine)) {
        return;
    }
    const next = `${current.trimEnd()}\n${exportLine}\n`;
    fs.writeFileSync(filePath, next);
}

function appendRustMod(filePath: string, modLine: string): void {
    const current = fs.readFileSync(filePath, 'utf-8');
    if (current.includes(modLine)) {
        return;
    }
    const marker = 'pub(crate) mod r#reputation_stats;';
    const next = current.includes(marker)
        ? current.replace(marker, `${modLine}\n${marker}`)
        : `${current.trimEnd()}\n${modLine}\n`;
    fs.writeFileSync(filePath, next);
}

function appendRustUse(filePath: string, useLine: string): void {
    const current = fs.readFileSync(filePath, 'utf-8');
    if (current.includes(useLine)) {
        return;
    }
    const marker = 'pub use self::r#reputation_stats::*;';
    const next = current.includes(marker)
        ? current.replace(marker, `${useLine}\n${marker}`)
        : `${current.trimEnd()}\n${useLine}\n`;
    fs.writeFileSync(filePath, next);
}
