pub const protocol_version = "0.1.0";

pub const supported_actions = [_][]const u8{
    "schema",
    "version",
    "providersList",
    "runtimeInfo",
    "cachePolicy",
    "policyCheck",
    "normalizeChain",
    "assetsResolve",
    "chainsTop",
    "chainsAssets",
    "yieldOpportunities",
    "bridgeQuote",
    "swapQuote",
    "lendMarkets",
    "lendRates",
    "normalizeAmount",
    "cachePut",
    "cacheGet",
    "rpcCallCached",
    "getBalance",
    "getErc20Balance",
    "getBlockNumber",
    "buildTransferNative",
    "buildTransferErc20",
    "buildErc20Approve",
    "buildDexSwap",
    "planLendingAction",
    "paymentIntentCreate",
    "subscriptionIntentCreate",
    "estimateGas",
    "sendSignedTransaction",
};
